
# Copyright 2020 The HuggingFace Datasets Authors and the current dataset script contributor.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# TODO: Address all TODOs and remove all explanatory comments
"""FairytaleQA: An Authentic Dataset for children's Narrative Comprehension """


import csv
import json
import os

import datasets

logger = datasets.logging.get_logger(__name__)



# TODO: Add BibTeX citation
# Find for instance the citation on arxiv or on the dataset repo/website
_CITATION = """\
@inproceedings{xu2022fairytaleqa,
    author={Xu, Ying and Wang, Dakuo and Yu, Mo and Ritchie, Daniel and Yao, Bingsheng and Wu, Tongshuang and Zhang, Zheng and Li, Toby Jia-Jun and Bradford, Nora and Sun, Branda and Hoang, Tran Bao and Sang, Yisi and Hou, Yufang and Ma, Xiaojuan and Yang, Diyi and Peng, Nanyun and Yu, Zhou and Warschauer, Mark},
    title = {Fantastic Questions and Where to Find Them: Fairytale{QA} -- An Authentic Dataset for Narrative Comprehension},
    publisher = {Association for Computational Linguistics},
    year = {2022}
}
"""

# TODO: Add description of the dataset here
# You can copy an official description
_DESCRIPTION = """\
The FairytaleQA dataset focusing on narrative comprehension of kindergarten to eighth-grade students. Generated by educational experts based on an evidence-based theoretical framework, FairytaleQA consists of 10,580 explicit and implicit questions derived from 278 children-friendly stories, covering seven types of narrative elements or relations. This is for the Question Generation Task of FairytaleQA.
"""

# TODO: Add a link to an official homepage for the dataset here
_HOMEPAGE = "https://github.com/uci-soe/FairytaleQAData"

# TODO: Add the licence for the dataset here if you can find it
_LICENSE = ""

# TODO: Add link to the official dataset URLs here
# The HuggingFace Datasets library doesn't host the datasets but only points to the original files.
# This can be an arbitrary nested dict/list of URLs (see below in `_split_generators` method)

_URLS = {
    "train": "train.json",
    "validation": "valid.json",
    "test": "test.json"
}


# TODO: Name of the dataset usually match the script name with CamelCase instead of snake_case
class FairytaleQA(datasets.GeneratorBasedBuilder):
    """TODO: Short description of my dataset."""

    # VERSION = datasets.Version("1.1.0")

    # This is an example of a dataset with multiple configurations.
    # If you don't want/need to define several sub-sets in your dataset,
    # just remove the BUILDER_CONFIG_CLASS and the BUILDER_CONFIGS attributes.

    # If you need to make complex sub-parts in the datasets with configurable options
    # You can create your own builder configuration class to store attribute, inheriting from datasets.BuilderConfig
    # BUILDER_CONFIG_CLASS = MyBuilderConfig

    # You will be able to load one or the other configurations in the following list with
    # data = datasets.load_dataset('my_dataset', 'first_domain')
    # data = datasets.load_dataset('my_dataset', 'second_domain')

    VERSION = datasets.Version("1.0.0")
    
    # DEFAULT_CONFIG_NAME = "fairytaleqa"

    # BUILDER_CONFIGS = [
    #     FairytaleQAConfig(
    #         name="plain_text", 
    #         description="Plain Text")
    # ]

    # DEFAULT_CONFIG_NAME = "train"  # It's not mandatory to have a default configuration. Just use one if it make sense.

    def _info(self):
        # TODO: This method specifies the datasets.DatasetInfo object which contains informations and typings for the dataset
        
        features = datasets.Features(
            {
                "story_name": datasets.Value("string"),
                "content": datasets.Value("string"),
                "answer": datasets.Value("string"),
                "gem_id": datasets.Value("string"),
                "target": datasets.Value("string"),
                "references":[datasets.Value("string")],
                "local_or_sum": datasets.Value("string"),
                "attribute": datasets.Value("string"),
                "ex_or_im": datasets.Value("string")
                # These are the features of your dataset like images, labels ...
            }
        )
        
        
        return datasets.DatasetInfo(
            # This is the description that will appear on the datasets page.
            description=_DESCRIPTION,
            # This defines the different columns of the dataset and their types
            features=features,  # Here we define them above because they are different between the two configurations
            # If there's a common (input, target) tuple from the features, uncomment supervised_keys line below and
            # specify them. They'll be used if as_supervised=True in builder.as_dataset.
            # supervised_keys=("sentence", "label"),
            supervised_keys=None,
            # Homepage of the dataset for documentation
            homepage=_HOMEPAGE,
            # License for the dataset if available
            license=_LICENSE,
            # Citation for the dataset
            citation=_CITATION,
        )

    def _split_generators(self, dl_manager):
        # TODO: This method is tasked with downloading/extracting the data and defining the splits depending on the configuration
        # If several configurations are possible (listed in BUILDER_CONFIGS), the configuration selected by the user is in self.config.name

        # dl_manager is a datasets.download.DownloadManager that can be used to download and extract URLS
        # It can accept any type or nested list/dict and will give back the same structure with the url replaced with path to local files.
        # By default the archives will be extracted and a path to a cached folder where they are extracted is returned instead of the archive
        # urls = _URLS[self.config.name]
        downloaded_files  = dl_manager.download_and_extract(_URLS)
        return [
            datasets.SplitGenerator(name=datasets.Split.TRAIN, gen_kwargs={
                "filepath": downloaded_files["train"], 
                "split": "train"}),
            datasets.SplitGenerator(name=datasets.Split.VALIDATION, gen_kwargs={
                "filepath": downloaded_files["validation"], 
                "split": "validation"}),
            datasets.SplitGenerator(name=datasets.Split.TEST, gen_kwargs={
                "filepath": downloaded_files["test"], 
                "split": "test"})
        ]

    # method parameters are unpacked from `gen_kwargs` as given in `_split_generators`
    def _generate_examples(self, filepath, split, filepaths=None, lang=None):
        # TODO: This method handles input defined in _split_generators to yield (key, example) tuples from the dataset.
        # The `key` is for legacy reasons (tfds) and is not important in itself, but must be unique for each example.
        logger.info("generating examples from = %s", filepath)

        with open(filepath, encoding="utf-8") as f:

            json_data = json.load(f)
            
            for id_, data in enumerate(json_data): 
                yield id_, {
                    "story_name": data['story_name'],
                    "content": data['content'],
                    "answer": data['answer'],
                    "gem_id": f"GEM-FairytaleQA-{split}-{id_}",
                    "target": data['question'],
                    "references": [] if split == "train" else [ data['question'] ],
                    "local_or_sum": data['local_or_sum'],
                    "attribute": data['attribute'],
                    "ex_or_im": data['ex_or_im']
                }


                
                